name: test1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: 2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true
